title: Myra Cheng
url: "https://myracheng.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Research"
   link: "https://scholar.google.com/citations?user=gaslQl8AAAAJ&hl=en"
 - name: "Teaching"
   link: "teaching"
