title: Myra Cheng
url: "https://myracheng.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: "Photo by Lilien Voong. Website template by Ankit Sultana."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Research"
   link: "research"
 - name: "Teaching"
   link: "teaching"
